spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.68:3306/insurance?autoReconnect=true&characterEncoding=UTF-8&useSSL=false
      username: tiger
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true

      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          config:
            multi-statement-allow: true

      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # nacos 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.68:8848
logging:
  level:
    com:
      haivera:
        insconadmin: debug
        insconuser: debug
